### PR TITLE
FEATURE: Add ability to specify custom date range on OpenMRS side, al…

### PR DESCRIPTION
**Pull request by mhawila**
…so handle non standard periods

### CODE REVIEW

**Comment by mhawila** [comment]
@kaweesi  there you go buddy.

**Comment by kaweesi** [comment]
Wow, thanks a lot man, i will get this reviewed and pulled in asap

**Comment by kaweesi** [comment]
do i need to manually edit the Date field when using the custom period type.

I pushed and got a null response, then downloading dxf returned me the entered period.
`{"dataSet":"zA0aTUoQ5K9","period":"201701","orgUnit":"xrRJDcNFiNf","dataValues":[{"dataElement":"RI4ZmnShzID","value":0,"comment":"Generated by DHIS Connector OpenMRS Module."},{"dataElement":"MD3LmmT5Rng","value":0,"comment":"Generated by DHIS Connector OpenMRS Module."},{"dataElement":"PuKJ2eMsHRz","value":0,"comment":"Generated by DHIS Connector OpenMRS Module."}]}`
CC; @mhawila

**Comment by kaweesi** [comment]
screen shot 2017-12-14 at 11 48 31

**Comment by kaweesi** [comment]
cool, so custom would mean even the entry in the Date field is the real period u are sending into DHIS2

**Comment by kaweesi** [comment]
thanks @mhawila 👍

**Pull request merged**
